### ISSUE TITLE
Linux: incorrect path due to link

### ISSUE THREAD

**Issue by az-z** [platformio/platformio-atom-ide#136]
on Linux soft link in project path is causing the platformio to incorrectly parse paths to an active file and project. That causes issues with building simultaneously open projects as described here (https://community.platformio.org/t/how-to-switch-the-project-in-the-ide/448)

**Comment by orgkhnargh** [comment]
Fixed by 88a4455e563f010398393b0363428ef619635b5f.

**Comment by ivankravets** [comment]
PlatformIO IDE 1.3.1 has been released. Please update it.

**Comment by az-z** [comment]
It seems the bug came back with the latest IDE.
Please check (https://community.platformio.org/t/atom-integration-failure-old-bug-resurfaced/1821/3)
