### ISSUE TITLE
InstallationManager: ENOENT: no such file or directory, open ~/packages/platformio-ide/.cache/examples.tar.gz

### ISSUE THREAD

**Issue by WillGreen98** [platformio/platformio-atom-ide#254]
Error: Error: ENOENT: no such file or directory, open '/Users/Will/.atom/packages/platformio-ide/.cache/examples.tar.gz'

**Comment by ivankravets** [comment]
Could you reproduce this issue after Atom restart?

**Comment by WillGreen98** [comment]
Yes, why? I have fixed the issue now though.

**Comment by ivankravets** [comment]
How did you resolve it?

**Comment by WillGreen98** [comment]
What OS are you using?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ivankravets** [comment]
I need information to fix this issue. What is your OS? Do you use Proxy?

**Comment by WillGreen98** [comment]
I use macOS and no, you do not need a proxy for platformio.

Will.

**Comment by ivankravets** [comment]
And how did you fix it?

**Comment by WillGreen98** [comment]
For macOS, I used homebrew to install the dependencies needed for platformio to be executed, I then linked those files to the directory of platformio, I installed core, terminal and IDE within atom and then restarted. Worked for me.

Will.

**Comment by ivankravets** [comment]
Wow! You don't need to do that. PlatformIO IDE has built-in PIO Core.

1. Try uninstall HomeBrew's PIO Core (`brew uninstall platformio`)
2. Remove all tracks of PIO Core in a system
3. Atom: Settings ⚙️ > Packages
4. Uninstall `platformio-ide` packages
5. Atom: Settings ⚙️ > Install > `platformio-ide`
6. IDE > Home > Switch to PlatformIO IDE 2.0
7. Does it work now?

It should work now. Please check that "Built-in PIO Core" is enabled in PIO IDE settings. Menu> PlatformIO > Settings > PlatformIO IDE

**Comment by WillGreen98** [comment]
I will try that for compiler errors but what I did worked for linking libraries and took like 30 seconds. For running and uploading code I will try your method. Thank you.

Will.

**Comment by WillGreen98** [comment]
I cannot see Built-in PIO Core in the settings.

Will.

**Comment by ivankravets** [comment]
Settings ⚙️ Packages > PlatformIO IDE > "use built-in PIO Core" shoud be checked

**Comment by WillGreen98** [comment]
Yes, that is checked, I have just found it.

Will.

**Comment by ivankravets** [comment]
Now please perform all steps from https://github.com/platformio/platformio-atom-ide/issues/254#issuecomment-285646404

I've deployed new PIO IDE 2.0 alpha build yesterday.

**Comment by WillGreen98** [comment]
Still getting upload errors, I wanted to use platformio for the autocorrect and intellisense but I might just use the arduino IDE.
Want this to work…Urg.

Will.

**Comment by ivankravets** [comment]
https://community.platformio.org/t/urgent-platformio-ide-2-0-preview-doesnt-receive-any-updates/1620/11
