### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by jsassner** [platformio/platformio-atom-ide#330]
This happens at start when PLATFORMIO_HOME_DIR env variable is set. When ENV var is unset, Atom starts just fine.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-beta.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At d:\Utilities\atom\.atom\packages\platformio-ide\lib\utils.js:143

TypeError: Cannot read property '0' of null
    at runCommand.cacheValid (/packages/platformio-ide/lib/utils.js:143:60)
    at /packages/platformio-ide/lib/utils.js:89:46
    at Array.map (native)
    at onExit (/packages/platformio-ide/lib/utils.js:89:36)
    at exit (/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -1:45 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocomplete-clang 0.10.1 
build 0.67.0 
busy 0.7.0 
clang-format 1.28.0 
file-icons 2.1.2 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.0 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
Please upgrade to the latest Beta 4. Should be fixed.

Atom > Settings > Updates

**Comment by Zarif25** [comment]
I am currently running 2.0.0-beta.8 and I have everything up to date but the error still exists.

**Comment by markdagraca** [comment]
@ivankravets I have this problem just downloaded atom and platform on a new a computer

**Comment by ivankravets** [comment]
@markdagraca could you provide full traceback?

**Comment by markdagraca** [comment]
@ivankravets  
TypeError: Cannot read property '0' of null
    at C:\Users\markd\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:167:58
    at ChildProcess.onExit (C:\Users\markd\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:492:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\markd\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by ivankravets** [comment]
Could you open system terminal `cmd` and type
```
platformio --version
```

Also,
```
C:\Users\markd\.platformio\penv\Scripts\activate
platformio --version
```

**Comment by markdagraca** [comment]
both of them say 3.4.1

**Comment by ivankravets** [comment]
Could you try to remove `C:\Users\markd\.platformio\penv` folder and restart Atom?

**Comment by markdagraca** [comment]
That works!!!! Thanks you, been trying to figure out this problem all day

**Comment by markdagraca** [comment]
now im getting this and the platform home page dosent load
![image](https://user-images.githubusercontent.com/25993277/30190030-654c1192-93ec-11e7-8813-40a200a1af45.png)

**Comment by markdagraca** [comment]
figured out the terminal error folder gotten set to read only the home page still dosent load though

**Comment by ivankravets** [comment]
Could you try temporary PIO IDE for VSCode?

- http://platformio.org/get-started/ide?install=vscode

**Comment by markdagraca** [comment]
home page dosent load either on vscode Unable to open 'PIO Home': Could not start PIO Home server: Error: timeout.

**Comment by ivankravets** [comment]
Do you have Microsoft Visual Studio installed in a system? (not VSCode)

**Comment by markdagraca** [comment]
im downloading it right now

**Comment by markdagraca** [comment]
could deleting the platform folder fix this issue

**Comment by ivankravets** [comment]
Could you explain in details how did you fix this issue? Does PIO Home work properly now?

**Comment by markdagraca** [comment]
no it still dosent work. Im asking if I delete the platform folder could that resolve the issue?

**Comment by markdagraca** [comment]
ok I have download visual studio what do you need me to do

**Comment by markdagraca** [comment]
tried deleting everything I could delete except for the folder "toolchain-atmelavr"

**Comment by markdagraca** [comment]
@ivankravets was able to delete the folder and reinstall it and it did not work here is what atom look like right now. no way to initialize the project and cannot see the platform home
![image](https://user-images.githubusercontent.com/25993277/30200713-f0a1ac94-942c-11e7-8e46-353fb84e16a8.png)

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by markdagraca** [comment]
@ivankravets here is what it cmd gave me 


C:\Users\markd>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\LLVM\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Users\markd\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\markd\AppData\Roaming\Dashlane\4.8.7.35982\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\markd\AppData\Roaming\Dashlane\4.8.7.35982\ucrt;C:\Users\markd\AppData\Local\GitHubDesktop\bin;C:\Users\markd\AppData\Local\atom\bin;C:\Python27;C:\Python27\Scripts

C:\Users\markd>echo %PYTHONPATH%
%PYTHONPATH%

C:\Users\markd>python --version
Python 2.7

C:\Users\markd>pip --version
pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)

C:\Users\markd>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
arrow (0.10.0)
bottle (0.12.13)
certifi (2017.7.27.1)
chardet (3.0.4)
click (5.1)
colorama (0.3.9)
idna (2.6)
lockfile (0.12.2)
pip (9.0.1)
platformio (3.4.1)
pyserial (3.4)
python-dateutil (2.6.1)
requests (2.18.4)
semantic-version (2.6.0)
setuptools (28.8.0)
six (1.10.0)
urllib3 (1.22)
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by markdagraca** [comment]
@ivankravets got it working now 100% by just factory restoring my computer and reinstalling everything
