### ISSUE TITLE
Annoying signup pop up at start !

### ISSUE THREAD

**Issue by danielbibit** [platformio/platformio-atom-ide#453]
After the last update, every time that I start Atom, a platformio popup comes up asking me to sign up. Apparently there's no configuration for disable this behavior, and is getting really annoying.

**Comment by ivankravets** [comment]
Please Menu: PlatformIO > Update PIO packages, libraries. It's is fixed in PIO Core+ 0.8.10

Then logout and login again. 

Please sorry

**Comment by ghs** [comment]
@ivankravets it is still happening here even after updating everything.

<img width="665" alt="captura de pantalla 2017-05-09 a las 9 48 30" src="https://cloud.githubusercontent.com/assets/94248/25840620/be0e0dbc-349c-11e7-94c7-723286877056.png">
<img width="635" alt="captura de pantalla 2017-05-09 a las 9 48 47" src="https://cloud.githubusercontent.com/assets/94248/25840619/bdfe6ace-349c-11e7-82f0-83a4539af444.png">

**Comment by ivankravets** [comment]
@orgkhnargh Please add a new item to IDE Settings after `showPIOHome` called `showPIOLogin`, "Show PIO Account Login on startup", which should be activated by default.

Please check this setting before showing PIO Account Login window.

**Comment by ivankravets** [comment]
@ghs which theme do you use?

**Comment by ghs** [comment]
Seti
